allowBuilds:
  "@swc/core": true
  cbor-extract: false
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@workflow/astro@4.0.19"
  - "@workflow/builders@4.1.9"
  - "@workflow/cli@4.3.8"
  - "@workflow/core@4.8.4"
  - "@workflow/nest@4.0.20"
  - "@workflow/next@4.1.8"
  - "@workflow/nitro@4.1.10"
  - "@workflow/nuxt@4.0.20"
  - "@workflow/rollup@4.0.19"
  - "@workflow/sveltekit@4.0.19"
  - "@workflow/vite@4.0.19"
  - "@workflow/web@4.1.20"
  - "@workflow/world-local@4.3.0"
  - "@workflow/world-vercel@4.7.0"
  - "@workflow/world@4.4.0"
  - workflow@4.8.4
overrides:
  nanoid@5.1.6: 5.1.16
  undici@7.28.0: 7.29.0
